-----------------INSERT CARRERAS-----------------

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería de Software')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Administración de Empresas')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería en Sistemas')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Derecho')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Diseñador Grafico')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería Electrónica')


 SELECT * FROM CARRERAS

  GO
 CREATE TABLE USUARIO(
 USERACCOUNT NVARCHAR(15) PRIMARY KEY NOT NULL,
 PASSWORD NVARCHAR(20) NOT NULL,
 PROFILEPICTURE IMAGE,
 CEDULA VARCHAR(9) UNIQUE NOT NULL,
 NOMBRE NVARCHAR(20) NOT NULL,
 APELLIDOS NVARCHAR (25) NOT NULL,
 SEXO NVARCHAR(15) NOT NULL,
 EMAIL NVARCHAR(30) NOT NULL,
 TELEFONO VARCHAR(12) NOT NULL,
 AREALAB VARCHAR(30) NOT NULL,)

 GO  
 if (OBJECT_ID ('ADDUSER', 'P')) is not null
    drop PROCEDURE ADDUSER;
 GO
 CREATE PROCEDURE ADDUSER
 @USERACCOUNT NVARCHAR(15),
 @PASSWORD NVARCHAR(20),
 @PROFILEPICTURE IMAGE,
 @CEDULA VARCHAR(9),
 @NOMBRE NVARCHAR(20),
 @APELLIDOS NVARCHAR,
 @SEXO NVARCHAR(15),
 @EMAIL NVARCHAR(30),
 @TELEFONO VARCHAR(12),
 @AREALAB VARCHAR(30)
 AS
 BEGIN
 INSERT INTO USUARIO VALUES(@USERACCOUNT,@PASSWORD,@PROFILEPICTURE,@CEDULA,@NOMBRE,@APELLIDOS,@SEXO,@EMAIL,@TELEFONO,@AREALAB)
 END

 GO
if (OBJECT_ID ('UPDPROFILE', 'P')) is not null
    DROP PROCEDURE UPDPROFILE;
GO
CREATE PROCEDURE UPDPROFILE
@PROFILEPICTURE IMAGE,
@USERACCOUNT NVARCHAR(15)
AS
BEGIN
	UPDATE USUARIO SET PROFILEPICTURE = @PROFILEPICTURE WHERE USERACCOUNT = @USERACCOUNT
END