-----------------INSERT CARRERAS-----------------

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería de Software')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Administración de Empresas')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería en Sistemas')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Derecho')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Diseñador Grafico')

 INSERT INTO CARRERAS(NOMBRE)
 VALUES('Ingeniería Electrónica')


/*--------------------------------------------------------------------------------------------------------------------------------*/
 GO  
 if (OBJECT_ID ('ADDUSER', 'P')) is not null
    drop PROCEDURE ADDUSER;
 GO
 CREATE PROCEDURE ADDUSER
 @USERACCOUNT NVARCHAR(15),
 @PASSWORD NVARCHAR(20),
 @PROFILEPICTURE IMAGE,
 @CEDULA VARCHAR(9),
 @NOMBRE NVARCHAR(20),
 @APELLIDOS NVARCHAR(25),
 @SEXO NVARCHAR(15),
 @EMAIL NVARCHAR(30),
 @TELEFONO VARCHAR(12),
 @AREALAB VARCHAR(30)
 AS
 BEGIN
 INSERT INTO USUARIO VALUES(@USERACCOUNT,@PASSWORD,@PROFILEPICTURE,@CEDULA,@NOMBRE,@APELLIDOS,@SEXO,@EMAIL,@TELEFONO,@AREALAB)
 END


/*--------------------------------------------------------------------------------------------------------------------------------*/
 GO
 if (OBJECT_ID ('UPDPROFILE', 'P')) is not null
     DROP PROCEDURE UPDPROFILE;
 GO
 CREATE PROCEDURE UPDPROFILE
 @PROFILEPICTURE IMAGE,
 @USERACCOUNT NVARCHAR(15)
 AS
 BEGIN
 	 UPDATE USUARIO SET PROFILEPICTURE = @PROFILEPICTURE WHERE USERACCOUNT = @USERACCOUNT
 END


/*--------------------------------------------------------------------------------------------------------------------------------*/
GO
if (OBJECT_ID ('UPSERVICE', 'P')) is not null
    DROP PROCEDURE UPSERVICE;
GO
CREATE PROCEDURE UPSERVICE
 @ID_SERVICIO VARCHAR(10),
 @NOMBRE_BRIN VARCHAR(25),
 @DESCRIPCION1 NVARCHAR(300),
 @AREA_BUSQ VARCHAR(30),
 @NOMBRE_BUSQ VARCHAR(25),
 @DESCRIPCION2 NVARCHAR(300),
 @VALORPROME FLOAT
AS
BEGIN
	UPDATE SERVICIO SET NOMBRE_BRIN = @NOMBRE_BRIN, DESCRIPCION1 = @DESCRIPCION1, AREA_BUSQ = @AREA_BUSQ, NOMBRE_BUSQ = @NOMBRE_BUSQ, DESCRIPCION2  = @DESCRIPCION2, VALORPROME = @VALORPROME WHERE ID_SERVICIO = @ID_SERVICIO
END


/*--------------------------------------------------------------------------------------------------------------------------------*/
SELECT         USUARIO.USERACCOUNT, USUARIO.CEDULA, USUARIO.NOMBRE, USUARIO.APELLIDOS, USUARIO.EMAIL, 
                          USUARIO.TELEFONO, USUARIO.AREALAB, SERVICIO.FECHA, SERVICIO.AREA_BRIN, 
                          SERVICIO.NOMBRE_BRIN, SERVICIO.DESCRIPCION1, SERVICIO.AREA_BUSQ, SERVICIO.NOMBRE_BUSQ, 
                          SERVICIO.DESCRIPCION2, SERVICIO.VALORPROME
FROM             USUARIO INNER JOIN
                          SERVICIO ON USUARIO.USERACCOUNT = SERVICIO.USERACCOUNT
WHERE         (SERVICIO.ID_SERVICIO = @ID_SERVICIO)